#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/



server:
  port: 8020
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

