#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/offers
    username: root
    password: pass@word1
  jpa:
    show-sql: true
      
